# Generated by Django 5.1.2 on 2024-11-01 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_name', models.CharField(max_length=100, unique=True)),
                ('grape_variety', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('status', models.CharField(choices=[('fermentation', 'Fermentation'), ('aging', 'Aging'), ('bottling', 'Bottling')], default='fermentation', max_length=20)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wine_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wine Batch',
                'verbose_name_plural': 'Wine Batches',
            },
        ),
    ]
