# Generated by Django 5.1.2 on 2024-11-01 21:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winebatch',
            options={},
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='lot_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='winebatch',
            unique_together={('user', 'lot_name')},
        ),
    ]
