# Generated by Django 5.1.2 on 2024-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0002_alter_winebatch_options_alter_winebatch_lot_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winebatch',
            name='grape_variety',
            field=models.CharField(choices=[('CS', 'Cabernet Sauvignon'), ('ME', 'Merlot'), ('CH', 'Chardonnay'), ('PN', 'Pinot Noir')], max_length=2),
        ),
    ]
