# Generated by Django 5.1.2 on 2024-11-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0004_analysis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='date_performed',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='alcohol',
            field=models.FloatField(default=0.0, verbose_name='Alcohol (%)'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='brix',
            field=models.FloatField(default=1, verbose_name='Brix'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='ph',
            field=models.FloatField(default=3.5, verbose_name='pH'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='so2',
            field=models.FloatField(default=0.0, verbose_name='SO₂'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='ta',
            field=models.FloatField(default=0.0, verbose_name='TA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='va',
            field=models.FloatField(default=0.0, verbose_name='VA'),
            preserve_default=False,
        ),
    ]
