# Generated by Django 5.1.2 on 2024-11-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0005_rename_date_performed_analysis_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='alcohol',
            field=models.FloatField(blank=True, null=True, verbose_name='Alcohol (%)'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='brix',
            field=models.FloatField(blank=True, null=True, verbose_name='Brix'),
        ),
    ]
