# Generated by Django 5.1.2 on 2024-11-03 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0006_alter_analysis_alcohol_alter_analysis_brix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='grape_variety',
            field=models.CharField(choices=[('CS', 'Cabernet Sauvignon'), ('ME', 'Merlot'), ('CH', 'Chardonnay'), ('PN', 'Pinot Noir'), ('RS', 'Riesling'), ('CF', 'Cabernet Franc'), ('PV', 'Petit Verdot')], max_length=2),
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(help_text='Capacity in liters')),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vessels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
