# Generated by Django 5.1.2 on 2024-11-03 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0007_alter_analysis_options_alter_winebatch_grape_variety_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='winebatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='winebatch',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wine_batches', to='wines.vessel'),
        ),
    ]
