# Generated by Django 5.1.2 on 2024-11-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0009_alter_analysis_options_vessel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='type',
            field=models.CharField(choices=[('tank', 'Tank'), ('barrel', 'Barrel')], default='tank', max_length=10),
        ),
    ]
