# Generated by Django 5.1.2 on 2024-11-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0010_alter_vessel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='winebatch',
            name='category',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Sparkling', 'Sparkling'), ('Dessert', 'Dessert'), ('Other', 'Other')], default='Red', max_length=10),
        ),
    ]
