# Generated by Django 5.1.2 on 2024-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0011_winebatch_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='winebatch',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='winebatch',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='winebatch',
            name='varietal',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='winebatch',
            name='vintage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='category',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Sparkling', 'Sparkling'), ('Dessert', 'Dessert'), ('Other', 'Other')], max_length=9),
        ),
    ]
