# Generated by Django 5.1.2 on 2024-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0012_winebatch_notes_winebatch_source_winebatch_varietal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winebatch',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
