# Generated by Django 5.1.2 on 2024-11-04 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0013_alter_winebatch_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winebatch',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='winebatch',
            name='user',
        ),
        migrations.AddField(
            model_name='winebatch',
            name='ava',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='winebatch',
            name='vineyard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='category',
            field=models.CharField(choices=[('red', 'Red'), ('white', 'White')], max_length=50),
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='grape_variety',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wines.vessel'),
        ),
        migrations.AlterField(
            model_name='winebatch',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
