# Generated by Django 5.1.2 on 2024-11-06 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0016_alter_winebatch_grape_variety'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='winebatch',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='wine_batches', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
