# Generated by Django 5.1.2 on 2024-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0017_winebatch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='date_added',
            field=models.DateField(default="2023-01-01"),  # Explicit date string as default
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vessel',
            name='fermentor_type',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White')], default='Red', max_length=5),
        ),
        migrations.AddField(
            model_name='vessel',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
