# Generated by Django 5.1.3 on 2024-11-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0019_analysis_notes_alter_vessel_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='vessel',
            name='current_capacity',
            field=models.IntegerField(default=0, help_text='Current volume of wine in liters'),
        ),
    ]
