# Generated by Django 5.1.3 on 2024-11-07 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0020_vessel_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='current_capacity',
        ),
        migrations.AddField(
            model_name='vessel',
            name='current_wine_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vessels', to='wines.winebatch'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='fermentor_type',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Sparkling', 'Sparkling')], default='Red', max_length=10),
        ),
    ]
