# Generated by Django 5.1.3 on 2024-11-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0022_vessel_current_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='winebatch',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),


        ),
    ]
