# Generated by Django 5.1.3 on 2024-11-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0023_winebatch_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winebatch',
            name='date_created',
        ),
    ]
