# Generated by Django 5.1.3 on 2024-11-08 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0025_winebatch_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vessel',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_vessel_per_user'),
        ),
    ]
