# Generated by Django 5.1.3 on 2024-11-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0026_vessel_unique_vessel_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='current_wine_batch',
            field=models.ForeignKey(blank=True, help_text='Select the current wine batch stored in this vessel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vessels', to='wines.winebatch'),
        ),
    ]
