# Generated by Django 5.1.3 on 2024-11-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0028_vessel_last_cleaned_date_vesselhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winebatch',
            name='grape_variety',
            field=models.CharField(choices=[('CS', 'Cabernet Sauvignon'), ('ME', 'Merlot'), ('CH', 'Chardonnay')], max_length=20),
        ),
    ]
