# Generated by Django 5.1.3 on 2024-11-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wines', '0029_alter_winebatch_grape_variety'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='Frequency of analysis during fermentation.', max_length=10),
        ),
    ]
